name: Go
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:

  build:
    name: Build

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        go: [ '1.11', '1.12', '1' ]
        redis: [ '5' ]
        rdbms:
          - mysql:5.7
          - mysql:8
          - mariadb:10.2
          - mariadb:10.3
          - mariadb:10

    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: ${{ matrix.rdbms }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: icingadb
          MYSQL_USER: icingadb
          MYSQL_PASSWORD: icingadb
        ports:
          - 3800:3306

      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Go Build
        run: go build -v -o icingadb .

      - name: Go Test
        env:
          ICINGADB_TEST_REDIS_HOST: 127.0.0.1
          ICINGADB_TEST_REDIS_PORT: 6379

          ICINGADB_TEST_MYSQL_HOST: 127.0.0.1
          ICINGADB_TEST_MYSQL_PORT: 3800
          ICINGADB_TEST_MYSQL_DATABASE: icingadb
          ICINGADB_TEST_MYSQL_USER: icingadb
          ICINGADB_TEST_MYSQL_PASSWORD: icingadb
        timeout-minutes: 10
        run: |
          while ! mysql -h ${ICINGADB_TEST_MYSQL_HOST} -P ${ICINGADB_TEST_MYSQL_PORT} \
            -u${ICINGADB_TEST_MYSQL_USER} -p${ICINGADB_TEST_MYSQL_PASSWORD} ${ICINGADB_TEST_MYSQL_DATABASE}
          do sleep 1
          done

          mysql -h ${ICINGADB_TEST_MYSQL_HOST} -P ${ICINGADB_TEST_MYSQL_PORT} \
            -u${ICINGADB_TEST_MYSQL_USER} -p${ICINGADB_TEST_MYSQL_PASSWORD} ${ICINGADB_TEST_MYSQL_DATABASE} \
            <etc/schema/mysql/mysql.schema.sql

          go test -v -race ./...
